# Kustomization with semantic versioning
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics

resources:
- deployment.yaml
- service.yaml

# Image versioning with semantic versions
# This is automatically updated by ArgoCD Image Updater to update the image tag in the deployment.yaml
images:
- name: globomantics/backend-api
  newTag: v2.1.1

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: globomantics
