# Kustomization with semantic versioning
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

# Image versioning with semantic versions
images:
- name: nginx
  newTag: 1.29.0

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: globomantics
