# Production overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-production

resources:
- ../../base
- namespace.yaml

patches:
- path: deployment-patch.yaml

commonLabels:
  env: production
